### PR TITLE
Various tweaks

### PR DESCRIPTION
**Pull request by jahidulpabelislam**
- ignore .idea folder (PHPStorm thing)
- minor html issues on popup.html
- fix issue on options page where if you go back to `-- project filter --` it shows no projects
- couple of tweaks to how the auto add logic:
    - .

### CODE REVIEW

**Review by JasonShallcross — APPROVED** [review]
👍

**Comment by jahidulpabelislam** [comment]
@JasonShallcross I've pushed one more commit but you are welcome to merge it if you are happy with it.

**Comment by jahidulpabelislam** [comment]
Thanks. Finally switched over from the old version you gave me 5 years ago. Was very handy and love this new version!

**Comment by JasonShallcross** [comment]
It's really nice to see someone else using it!

I'm sure there are plenty of improvements to be made.

Being able to export and import was a game changer.

**Pull request merged**
